language: generic
sudo: true

services:
  - docker
 
 
before_install:
- docker pull sumdoc/texlive-2017
- docker run -it -v /c/Users/username/Folder_with_tex:/home sumandoc/texlive-2017 bin/bash

###############################################################################
script:
  # Use this for simple DVI
  - latex -halt-on-error -interaction nonstopmode small2e
  # Use this for simple PDF
  - pdflatex -halt-on-error -interaction nonstopmode small2e
  # Use this for PDF with bibtex citations
  - pdflatex -halt-on-error -interaction nonstopmode sample_article &&
    bibtex sample_article &&
    pdflatex -halt-on-error -interaction nonstopmode sample_article &&
    pdflatex -halt-on-error -interaction nonstopmode sample_article
